FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/prod.txt && \
    adduser --disabled-password --gecos '' thekid && \
    chown -R thekid:thekid /app

USER thekid

ENV FLASK_APP=bereal.server

CMD ["celery", "-A", "bereal.celery", "flower", "--address=0.0.0.0", "--inspect", "--enable-events", "--loglevel=DEBUG", --"logfile=flower.log"]
