FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y git && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/prod.txt && \
    adduser --disabled-password --gecos '' thekid && \
    chown -R thekid:thekid /app

USER thekid

ENV FLASK_APP=bereal.server

CMD ["celery", "-A", "bereal.celery worker", "--loglevel=INFO", "--logfile=celery.log", "-E", "-c", "1"]
