FROM python:3.11

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y netcat-openbsd

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY --chmod=+x ./scripts/server-entrypoint.sh /app/

ENV FLASK_APP=bereal.server

RUN adduser --disabled-password --gecos '' thekid
RUN chown -R thekid:thekid /app && chmod -R 777 /app
USER thekid

EXPOSE 5000

ENTRYPOINT ["/app/server-entrypoint.sh"]
